# Generated by Django 4.2.11 on 2024-03-19 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('test_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('DEFAULT', 'Default'), ('LOW', 'Low')], default='DEFAULT', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('issue_tracker_ids', models.JSONField(default=list)),
                ('added_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_head', models.CharField(max_length=255)),
                ('triggered_by_user', models.CharField(max_length=255)),
                ('ci_job_id', models.CharField(max_length=255)),
                ('browser_info', models.TextField()),
                ('view_port_size', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('time_taken', models.DurationField()),
                ('errors', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testcase')),
                ('test_run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testrun')),
            ],
            options={
                'verbose_name': 'TestCaseStatus',
                'verbose_name_plural': 'TestCaseStatuses',
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testcasemodule'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('time_taken', models.DurationField()),
                ('new_tests_added', models.IntegerField()),
                ('tests_skipped', models.IntegerField()),
                ('tests_completed', models.IntegerField()),
                ('tests_failed', models.IntegerField()),
                ('test_run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.testrun')),
            ],
        ),
    ]
